#!/usr/bin/php
<?php

// php-cs-fixer rules

$rules =
[
	'no_trailing_whitespace',
	'no_whitespace_in_blank_line',
	'encoding',
	'single_blank_line_at_eof',
	'elseif',
	'blank_line_after_namespace',
	'blank_line_after_opening_tag',
	'cast_spaces',
	'hash_to_slash_comment',
	'lowercase_cast',
	'lowercase_constants',
	'lowercase_keywords',
	'no_alias_functions',
	'no_extra_consecutive_blank_lines',
	'no_leading_import_slash',
	'standardize_not_equals',
	'method_argument_space',
	'linebreak_after_opening_tag',
	'no_blank_lines_after_phpdoc',
	'no_leading_namespace_whitespace',
	'single_blank_line_before_namespace',
	'native_function_casing',
	'no_closing_tag',
	'no_singleline_whitespace_before_semicolons',
	'no_spaces_inside_parenthesis',
	'no_trailing_comma_in_list_call',
	'no_trailing_comma_in_singleline_array',
	'no_trailing_whitespace_in_comment',
	'no_whitespace_before_comma_in_array',
	'object_operator_without_whitespace',
	'phpdoc_align',
];

// Check if we have php-cs-fixer in the path and exit if we don't

$fixer = trim(shell_exec('which php-cs-fixer'));

if(empty($fixer))
{
    exit(1);
}

// Get the list of modified files and run PHP files through the php-cs-fixer

exec('git diff --cached --name-status', $output);

foreach($output as $file)
{
	if(substr($file, 0, 1) !== 'M')
	{
		continute; // File isn't modified so we'll just skip it
	}

	$file = trim(substr($file, 1));

	if(file_exists($file) && pathinfo($file, PATHINFO_EXTENSION) === 'php')
	{
		exec($fixer . ' fix ' . $file . ' --rules=' . implode(',', $rules));

		exec('git add ' . $file);
	}
}
